name: Check Vendista
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Load data
        uses: actions/cache@v3
        with:
          path: |
            last_time.txt
            cash.txt
          key: vendista-data-v1
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4
        
      - name: Run script
        run: python main.py
        env:
          COOKIE_PART1: ${{ secrets.COOKIE_PART1 }}
          COOKIE_PART2: ${{ secrets.COOKIE_PART2 }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          
      - name: Save data
        uses: actions/cache@v3
        with:
          path: |
            last_time.txt
            cash.txt
          key: vendista-data-v1
